from dotenv import dotenv_values

config = dotenv_values(".env")

BOT_API_KEY = config.get("BOT_API_KEY")
ADMIN_ID = config.get("ADMIN_ID")
MONGO_DB_USERNAME = config.get("MONGO_DB_USERNAME")
MONGO_DB_PASSWORD = config.get("MONGO_DB_PASSWORD")


MIN_COUNT_SYMBOLS = 15
MAX_COUNT_SYMBOLS = 100

USER_PROFILE_PICTURE = "AgACAgIAAxkBAAIDFWhniNnlg57V82BizYfHc1nBiz3VAALp8jEbg3VAS98yh2TO5O79AQADAgADeQADNgQ"
MATCH_MENU_PICTURE = "AgACAgIAAxkBAAIDG2hniWKMMZHagFbpGe9_Kn2KxTdNAALq8jEbg3VASzK6PDhuBbsYAQADAgADeQADNgQ"
SEARCH_MENU_PICTURE = "AgACAgIAAxkBAAIDHmhniXNyAc8cH4YWgrLDMjjBc2NSAALr8jEbg3VAS8X0z5G5JvcFAQADAgADeQADNgQ"